'use strict';
angular.module('controller')
.controller('myaddrController',['$scope','$state','$filter','Restangular','$http','baseUrl','user',function(s,$state,$filter,rest,$http,baseUrl,user){
    var addr=rest.all(baseUrl+'api').one("center",'address');
    s.addrs=addr.get({wxOpenid:user.get("wxOpenid")}).$object;
    s.setDefault=function(addr){
        if(~~addr.isDefault===1){
            return;
        }
        $http.post(baseUrl+"api/center/setDefaultAddress",{id:addr.id+""})
        .success(function(d){
            if(d.code!=200){
                alert(d.msg);
            }else{
                $state.reload();
            }
        }).error(function(d){
            console.log(d);
            alert(d);
        });
    }
    s.delete=function(e,address){        
        e.stopPropagation();
        var b=confirm("是否删除该地址?");
        if(b){
            addr.remove({id:address.id}).then(function(d){
                if(d.code!=200){
                    alert(d.msg);
                }else{
                    alert("删除成功");
                    $state.reload();
                }
            },function(d){
                alert($filter('json')(d));
            });
        }else{
        }        
    }
    s.edit=function(e,addr){        
        e.stopPropagation();
        $state.go("editAddr",{id:addr.id});
    }
}]);