'use strict';
angular.module('controller')
.controller('myaddrController',['$scope','$state',function(s,$state){
    var addrs=[
        {
            name:'张三',
            tel:'13100000000',
            addr:'广东省深圳市华侨城创意文化园a3栋208c',
            "default":true    
        },
        {
            name:'李四',
            tel:'13100000000',
            addr:'广东省深圳市华侨城创意文化园a3栋208c',
            "default":false   
        },
        {
            name:'王五',
            tel:'13100000000',
            addr:'广东省深圳市华侨城创意文化园a3栋208c',
            "default":false   
        }
    ];
    s.addrs=addrs;
    s.test=function(){
        console.log(Date());
    }
    s.delete=function(e){        
        e.stopPropagation();
    }
    s.edit=function(e){        
        e.stopPropagation();
        $state.go("editAddr",{id:123});
    }
}]);