'use strict';
angular.module('controller')
.controller('paymentController',['$scope','order','wx','$filter','$http','baseUrl','user','$q','$state',function(s,order,wx,$filter,$http,baseUrl,user,$q,$state){
    s.orderHead=order.orderHead;
    s.orderBody=order.orderBody;
    
    s.ctip="正在查找优惠券";
    $http.get(baseUrl+"api/coupons/getCouponsUseable",{
        cache:false,
        params:angular.extend({},{
            wxOpenid:user.get('wxOpenid'),
            orderID:s.orderHead.orderID
        })
    }).success(function(d){
        if(d.code!=200){
            console.log(d.msg);
            s.ctips=d.msg;
        }else{
            s.coupons=d.data;  
            if(d.data.length!=0){
              s.ctip="未选择";
            }else{
              s.ctip="无可用优惠券";
            }
        }
    }).error(function(d){
        s.ctip="查找失败";
    });
    s.$watch("coupon",function(coupon){
        if(!coupon){
            s.pay_display=orderHead.totlePrice;
        }else{
            if(coupon.cardType==99){
                s.pay_display=1;    
            }else{
                s.pay_display=orderHead.totlePrice-coupon.cardPrice;    
            }
        }
    });
    function pay(){
      wx.payNewVer({
        orderID:s.orderHead.orderID,
        customerCardID:s.coupon&&s.coupon.customerCardID||null
      }).then(function(d){
        alert("您已付款成功");
        $state.go('order');
      },function(d){
        if(d=="fail"){
            alert("支付失败.");
        }
      });
    };
    s.pay=pay;   
}]);