'use strict';
angular.module('controller')
.controller('paymentController',['$scope','order','wx','$filter','$http','baseUrl','user',function(s,order,wx,$filter,$http,baseUrl,user){
    s.orderHead=order.orderHead;
    s.orderBody=order.orderBody;
    s.coupon={};
    s.ctip="正在查找优惠券";
    $http.get(baseUrl+"api/coupons/getCustomerCoupons",{
        cache:false,
        params:angular.extend({},{wxOpenid:user.get('wxOpenid')})
    }).success(function(d){
        if(d.code!=200){
            console.log(d.msg);
            s.ctips=d.msg;
        }else{
            s.coupons=d.data;  
            if(d.data.length!=0){
              s.ctip="请选择优惠券";
            }else{
              s.ctip="无可用优惠券";
            }
        }
    }).error(function(d){
        s.ctip="查找失败";
    }); 
    function pay(){
      wx.payNewVer({
        orderID:s.orderHead.orderID,
        customerCardID:s.coupon.customerCardID
      });
    };
    s.pay=pay;
}]);